/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipos_pu;

import java.awt.*;
import java.awt.geom.*;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;

/**
 Home page for browsing products, promotions, and customer actions in IPOS-PU.
 *
 * @author nuhur
 */
public class HomePage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    private String username;
    private int cartCount = 0;
    private DefaultTableModel productModel;
    private Object[][] allProductData;
    private String activePromo = null;
    private JTable productTable;
    private JLabel promoBannerLbl;
    private JLabel loyaltyBannerLbl;
    private Integer activeCampaignId = null;

    private final java.util.Map<Integer, PromotionCardData> campaignsById = new java.util.HashMap<>();

    /**
     Stores the data needed to display and apply a promotion campaign.
     */
    private static class PromotionCardData {
        Integer campaignId;
        String campaignName;
        String startDatetime;
        String endDatetime;
        java.util.Map<String, Double> discountsByProductId = new java.util.HashMap<>();
        java.util.Map<String, Double> discountsByProductName = new java.util.HashMap<>();
    }

    private final java.util.Map<String, Integer> stockQtyMap   = new java.util.HashMap<>();
    private final java.util.Map<String, Integer> stockLimitMap = new java.util.HashMap<>();

    /**
     * Creates new form HomePage with a known username.
     */
    public HomePage(String username) {
        this.username = username;
        initComponents();
        styleComponents();
        ActivityLoggerClient.log("CATALOGUE_VIEW", null, null, null);
    }

    /**
     * Creates new form HomePage (defaults to "Guest").
     */
    public HomePage() {
        this("Guest");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        brandLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        searchField = new javax.swing.JTextField();
        cartButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        mainScroll = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        sectionPromoLabel = new javax.swing.JLabel();
        promoPanel = new javax.swing.JPanel();
        cataloguePanel = new javax.swing.JPanel();
        filterRow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navPanel.setLayout(new javax.swing.BoxLayout(navPanel, javax.swing.BoxLayout.X_AXIS));

        brandLabel.setText("IPOS-PU");
        navPanel.add(brandLabel);
        navPanel.add(filler1);
        navPanel.add(filler2);

        searchField.setText("jTextField1");
        searchField.addActionListener(this::searchFieldActionPerformed);
        navPanel.add(searchField);

        cartButton.setText("Cart");
        navPanel.add(cartButton);

        signOutButton.setText("Sign Out");
        navPanel.add(signOutButton);

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.X_AXIS));

        sectionPromoLabel.setText("FEATURED PROMOTIONS");
        contentPanel.add(sectionPromoLabel);
        contentPanel.add(promoPanel);

        cataloguePanel.setLayout(new javax.swing.BoxLayout(cataloguePanel, javax.swing.BoxLayout.Y_AXIS));
        cataloguePanel.add(filterRow);

        contentPanel.add(cataloguePanel);

        mainScroll.setViewportView(contentPanel);

        navPanel.add(mainScroll);

        getContentPane().add(navPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }


    private static final Color BG      = new Color(0x05080f);
    private static final Color PANEL   = new Color(0x080e1a);
    private static final Color NEON    = new Color(0x2563A8);
    private static final Color NEON_LT = new Color(0x7eb8f7);

    /**
     Builds and styles the home page layout, navigation, and main content.
     */
    private void styleComponents() {
        setTitle("IPOS-PU · Home");
        setSize(1280, 760);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new Dimension(1000, 620));
        setLocationRelativeTo(null);
        getContentPane().setBackground(BG);

        navPanel.remove(mainScroll);
        getContentPane().add(mainScroll, BorderLayout.CENTER);

        navPanel.setBackground(PANEL);
        navPanel.setPreferredSize(new Dimension(0, 58));
        navPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37, 99, 168, 90)),
                BorderFactory.createEmptyBorder(0, 20, 0, 20)
        ));

        navPanel.removeAll();
        brandLabel.setText("<html><span style='font-family:Trebuchet MS;font-size:16px;"
                + "font-weight:bold;color:#ffffff'>IPOS</span><span style='font-family:Trebuchet MS;"
                + "font-size:16px;font-weight:bold;color:#7eb8f7'>-PU</span></html>");
        navPanel.add(brandLabel);
        navPanel.add(filler1);

        JLabel welcomeLabel = new JLabel("Hi, " + (username != null && !username.isEmpty() ? username : "Guest"));
        welcomeLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        welcomeLabel.setForeground(new Color(255, 255, 255, 110));
        navPanel.add(welcomeLabel);
        navPanel.add(Box.createHorizontalStrut(16));

        Box.Filler leftGlue = new Box.Filler(
                new Dimension(0, 0), new Dimension(0, 0), new Dimension(Short.MAX_VALUE, 0));
        navPanel.add(leftGlue);

        searchField.setText("");
        searchField.setBackground(new Color(0x0b1220));
        searchField.setForeground(new Color(255, 255, 255, 80));
        searchField.setCaretColor(NEON_LT);
        searchField.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        searchField.setMaximumSize(new Dimension(380, 34));
        searchField.setPreferredSize(new Dimension(380, 34));
        searchField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(37, 99, 168, 100), 1),
                BorderFactory.createEmptyBorder(6, 12, 6, 12)
        ));
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override public void focusGained(java.awt.event.FocusEvent e) {
                searchField.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(NEON_LT, 1),
                        BorderFactory.createEmptyBorder(6, 12, 6, 12)
                ));
            }
            @Override public void focusLost(java.awt.event.FocusEvent e) {
                searchField.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(37, 99, 168, 100), 1),
                        BorderFactory.createEmptyBorder(6, 12, 6, 12)
                ));
            }
        });
        navPanel.add(searchField);
        navPanel.add(filler2);

        cartButton.setText("Cart");
        cartButton.setMaximumSize(new Dimension(100, 34));
        cartButton.setPreferredSize(new Dimension(100, 34));
        cartButton.setFocusPainted(false);
        cartButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        cartButton.setOpaque(true);
        cartButton.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                int w = c.getWidth(), h = c.getHeight();
                g2.setColor(new Color(0x0b1220));
                g2.fillRect(0, 0, w, h);
                g2.setColor(new Color(37, 99, 168, 80));
                g2.setStroke(new BasicStroke(1f));
                g2.drawRect(0, 0, w - 1, h - 1);
                g2.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                g2.setColor(new Color(255, 255, 255, 160));
                String text = "Cart";
                FontMetrics fm = g2.getFontMetrics();
                g2.drawString(text, (w - fm.stringWidth(text)) / 2,
                        (h + fm.getAscent() - fm.getDescent()) / 2);

                if (cartCount > 0) {
                    String badge = String.valueOf(cartCount);
                    g2.setFont(new Font("Segoe UI", Font.BOLD, 9));
                    FontMetrics bfm = g2.getFontMetrics();
                    int bw = Math.max(14, bfm.stringWidth(badge) + 6);
                    int bx = w - bw - 3, by = 3;
                    g2.setColor(new Color(0xef4444));
                    g2.fillOval(bx, by, bw, 14);
                    g2.setColor(Color.WHITE);
                    g2.drawString(badge, bx + (bw - bfm.stringWidth(badge)) / 2,
                            by + bfm.getAscent() - 1);
                }
                g2.dispose();
            }
        });
        cartButton.addActionListener(e -> {
            dispose();
            new CartPage(username).setVisible(true);
        });
        navPanel.add(cartButton);

        signOutButton.setBackground(NEON);
        signOutButton.setForeground(Color.WHITE);
        signOutButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        signOutButton.setBorder(BorderFactory.createEmptyBorder(8, 18, 8, 18));
        signOutButton.setFocusPainted(false);
        signOutButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        signOutButton.setOpaque(true);
        signOutButton.addActionListener(e -> {
            CartManager.clear();
            OrderManager.clear();
            dispose();
            new LandingPage().setVisible(true);
        });
        navPanel.add(signOutButton);
        navPanel.add(Box.createHorizontalStrut(12));
        navPanel.add(makeAvatarPanel());

        mainScroll.setBorder(null);
        mainScroll.getViewport().setBackground(BG);
        mainScroll.getVerticalScrollBar().setUnitIncrement(16);

        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setBackground(BG);
        contentPanel.setBorder(BorderFactory.createEmptyBorder(22, 28, 28, 28));

        sectionPromoLabel.setFont(new Font("Segoe UI", Font.BOLD, 11));
        sectionPromoLabel.setForeground(NEON);
        sectionPromoLabel.setAlignmentX(LEFT_ALIGNMENT);
        sectionPromoLabel.setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0));

        promoPanel.setOpaque(false);
        promoPanel.setAlignmentX(LEFT_ALIGNMENT);
        promoPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 190));
        buildPromoCards();

        JLabel sectionCatLabel = new JLabel("PRODUCT CATALOGUE");
        sectionCatLabel.setFont(new Font("Segoe UI", Font.BOLD, 11));
        sectionCatLabel.setForeground(NEON);
        sectionCatLabel.setAlignmentX(LEFT_ALIGNMENT);
        sectionCatLabel.setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0));
        cataloguePanel.add(sectionCatLabel, 0);

        cataloguePanel.setBackground(BG);
        cataloguePanel.setAlignmentX(LEFT_ALIGNMENT);

        cataloguePanel.remove(filterRow);

        buildProductTable();

        if (!"Guest".equals(username)) {
            contentPanel.add(Box.createVerticalStrut(24));
            contentPanel.add(buildCustomerServices());
        }

        contentPanel.revalidate();
        contentPanel.repaint();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override public void windowOpened(java.awt.event.WindowEvent e) {
                int viewH  = mainScroll.getViewport().getHeight();
                int contH  = contentPanel.getPreferredSize().height;
                if (viewH > contH) {
                    contentPanel.setPreferredSize(
                            new Dimension(contentPanel.getPreferredSize().width, viewH));
                    contentPanel.revalidate();
                }
            }
        });

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke('/'), "focusSearch");
        getRootPane().getActionMap().put("focusSearch", new javax.swing.AbstractAction() {
            @Override public void actionPerformed(java.awt.event.ActionEvent e) {
                searchField.requestFocusInWindow();
                searchField.selectAll();
            }
        });
    }

    /**
     Styles a navigation button used in the top bar.
     */
    private void styleNavBtn(JButton btn) {
        btn.setBackground(new Color(0x0b1220));
        btn.setForeground(new Color(255, 255, 255, 160));
        btn.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btn.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(37, 99, 168, 80), 1),
                BorderFactory.createEmptyBorder(6, 14, 6, 14)
        ));
        btn.setFocusPainted(false);
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btn.setOpaque(true);
    }

    /**
     Loads active promotion campaigns from the backend.
     */
    private java.util.List<PromotionCardData> loadActiveCampaignsFromBackend() {
        java.util.List<PromotionCardData> campaigns = new java.util.ArrayList<>();
        campaignsById.clear();

        try {
            java.net.URL url = new java.net.URL("http://localhost:8080/api/promotions/active");
            java.net.HttpURLConnection conn = (java.net.HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");

            int status = conn.getResponseCode();
            String response = "";
            try {
                response = new String(
                        (status >= 200 && status < 300 ? conn.getInputStream() : conn.getErrorStream()).readAllBytes()
                );
            } catch (Exception ignored) {}

            System.out.println("ACTIVE CAMPAIGNS status = " + status);
            System.out.println("ACTIVE CAMPAIGNS response = " + response);

            if (status >= 400) {
                return campaigns;
            }

            int arrStart = response.indexOf("[");
            int arrEnd = response.lastIndexOf("]");
            if (arrStart == -1 || arrEnd == -1 || arrEnd <= arrStart) {
                return campaigns;
            }

            String itemsArray = response.substring(arrStart + 1, arrEnd).trim();
            if (itemsArray.isEmpty()) {
                return campaigns;
            }

            String[] objects = itemsArray.split("\\},\\s*\\{");
            for (String obj : objects) {
                String clean = obj;
                if (!clean.startsWith("{")) clean = "{" + clean;
                if (!clean.endsWith("}")) clean = clean + "}";

                PromotionCardData card = new PromotionCardData();

                String campaignIdStr = extract(clean, "campaignId");
                String campaignName = extract(clean, "campaignName");
                String startDatetime = extract(clean, "startDatetime");
                String endDatetime = extract(clean, "endDatetime");

                if (campaignIdStr == null) continue;

                try {
                    card.campaignId = Integer.parseInt(campaignIdStr);
                } catch (Exception ex) {
                    continue;
                }

                card.campaignName = campaignName;
                card.startDatetime = startDatetime;
                card.endDatetime = endDatetime;

                loadPromotionProductsForCampaign(card);

                campaigns.add(card);
                campaignsById.put(card.campaignId, card);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return campaigns;
    }
    /**
     Loads product discounts for a promotion campaign from the backend.
     */
    private void loadPromotionProductsForCampaign(PromotionCardData card) {
        if (card == null || card.campaignId == null) return;

        try {
            java.net.URL url = new java.net.URL(
                    "http://localhost:8080/api/promotions/products?campaignId=" + card.campaignId
            );
            java.net.HttpURLConnection conn = (java.net.HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");

            int status = conn.getResponseCode();
            String response = "";
            try {
                response = new String(
                        (status >= 200 && status < 300 ? conn.getInputStream() : conn.getErrorStream()).readAllBytes()
                );
            } catch (Exception ignored) {}

            System.out.println("PROMOTION PRODUCTS status = " + status);
            System.out.println("PROMOTION PRODUCTS response = " + response);

            if (status >= 400) return;

            int productsKey = response.indexOf("\"products\"");
            if (productsKey == -1) return;

            int arrStart = response.indexOf("[", productsKey);
            int arrEnd = response.lastIndexOf("]");
            if (arrStart == -1 || arrEnd == -1 || arrEnd <= arrStart) return;

            String itemsArray = response.substring(arrStart + 1, arrEnd).trim();
            if (itemsArray.isEmpty()) return;

            String[] objects = itemsArray.split("\\},\\s*\\{");
            for (String obj : objects) {
                String clean = obj;
                if (!clean.startsWith("{")) clean = "{" + clean;
                if (!clean.endsWith("}")) clean = clean + "}";

                String productId = extract(clean, "productId");
                String name = extract(clean, "name");
                String discountRateStr = extract(clean, "discountRate");

                if (discountRateStr == null) continue;

                try {
                    double discountRate = Double.parseDouble(discountRateStr);

                    if (productId != null) {
                        card.discountsByProductId.put(productId, discountRate);
                    }
                    if (name != null) {
                        card.discountsByProductName.put(name, discountRate);
                    }
                } catch (Exception ignored) {}
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     Extracts a field value from a simple JSON string.
     */
    private String extract(String json, String key) {
        String search = "\"" + key + "\"";
        int start = json.indexOf(search);
        if (start == -1) return null;

        int colon = json.indexOf(":", start);
        if (colon == -1) return null;

        int valueStart = colon + 1;
        while (valueStart < json.length() && Character.isWhitespace(json.charAt(valueStart))) {
            valueStart++;
        }

        if (valueStart >= json.length()) return null;

        if (json.charAt(valueStart) == '"') {
            int endQuote = json.indexOf("\"", valueStart + 1);
            if (endQuote == -1) return null;
            return json.substring(valueStart + 1, endQuote);
        }

        int end = valueStart;
        while (end < json.length()
                && json.charAt(end) != ','
                && json.charAt(end) != '}'
                && !Character.isWhitespace(json.charAt(end))) {
            end++;
        }

        return json.substring(valueStart, end);
    }

    /**
     Builds the promotion card area using the active campaigns.
     */
    private void buildPromoCards() {
        promoPanel.removeAll();

        java.util.List<PromotionCardData> active = loadActiveCampaignsFromBackend();
        java.util.List<JPanel> cards = new java.util.ArrayList<>();

        for (PromotionCardData camp : active) {
            final Integer id = camp.campaignId;
            cards.add(makePromoCard(camp, () -> activatePromo(id)));
        }

        if (cards.isEmpty()) {
            promoPanel.setLayout(new BorderLayout());
            JLabel none = new JLabel("No promotions are currently active.");
            none.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            none.setForeground(new Color(255, 255, 255, 60));
            promoPanel.add(none, BorderLayout.WEST);
        } else {
            promoPanel.setLayout(new GridLayout(1, cards.size(), 14, 0));
            for (JPanel c : cards) promoPanel.add(c);
        }

        promoPanel.revalidate();
        promoPanel.repaint();
    }

    /**
     Builds a promotion card for an active campaign.
     */
    private JPanel makePromoCard(PromotionCardData camp, Runnable onClick) {
        StringBuilder discSb = new StringBuilder();
        for (java.util.Map.Entry<String, Double> e : camp.discountsByProductName.entrySet()) {
            if (discSb.length() > 0) discSb.append(", ");
            discSb.append(e.getKey()).append(" ").append((int) Math.round(e.getValue())).append("% off");
        }
        String desc = discSb.length() > 0 ? discSb.toString() : "Special discount event";

        JPanel card = new JPanel() {
            @Override protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gp = new GradientPaint(0, 0, new Color(0x0d1b33),
                        getWidth(), getHeight(), new Color(0x080e1a));
                g2.setPaint(gp);
                g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 12, 12));
                g2.setColor(new Color(37, 99, 168, 76));
                g2.setStroke(new BasicStroke(1f));
                g2.draw(new RoundRectangle2D.Float(0.5f, 0.5f, getWidth() - 1f, getHeight() - 1f, 12, 12));
                RadialGradientPaint rg = new RadialGradientPaint(
                        new Point(getWidth(), 0), 90,
                        new float[]{0f, 1f},
                        new Color[]{new Color(37, 99, 168, 50), new Color(0, 0, 0, 0)}
                );
                g2.setPaint(rg);
                g2.fillRect(0, 0, getWidth(), getHeight());
                g2.dispose();
            }
        };
        card.setOpaque(false);
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(BorderFactory.createEmptyBorder(16, 18, 16, 18));

        JLabel tagLbl = new JLabel("PROMO");
        tagLbl.setFont(new Font("Segoe UI", Font.BOLD, 9));
        tagLbl.setForeground(NEON_LT);

        JLabel nameLbl = new JLabel(camp.campaignName != null ? camp.campaignName : "Promotion");
        nameLbl.setFont(new Font("Trebuchet MS", Font.BOLD, 14));
        nameLbl.setForeground(Color.WHITE);

        JLabel descLbl = new JLabel("<html><div style='width:160px'>" + desc + "</div></html>");
        descLbl.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        descLbl.setForeground(new Color(255, 255, 255, 115));

        String dateText = "";
        if ((camp.startDatetime != null && !camp.startDatetime.isEmpty())
                || (camp.endDatetime != null && !camp.endDatetime.isEmpty())) {
            String s = camp.startDatetime != null ? camp.startDatetime.replace("T", " ") : "Now";
            String e = camp.endDatetime != null ? camp.endDatetime.replace("T", " ") : "Ongoing";
            dateText = s + " — " + e;
        }

        JLabel dateLbl = new JLabel(dateText);
        dateLbl.setFont(new Font("Segoe UI", Font.PLAIN, 10));
        dateLbl.setForeground(new Color(255, 255, 255, 80));
        dateLbl.setVisible(!dateText.isEmpty());

        JLabel ctaLbl = new JLabel("APPLY PROMO");
        ctaLbl.setFont(new Font("Segoe UI", Font.BOLD, 10));
        ctaLbl.setForeground(NEON);
        ctaLbl.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        card.add(tagLbl);
        card.add(Box.createVerticalStrut(5));
        card.add(nameLbl);
        card.add(Box.createVerticalStrut(4));
        card.add(descLbl);
        card.add(Box.createVerticalStrut(6));
        card.add(dateLbl);
        card.add(Box.createVerticalGlue());
        card.add(Box.createVerticalStrut(4));
        card.add(ctaLbl);

        card.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        java.awt.event.MouseAdapter promoClick = new java.awt.event.MouseAdapter() {
            @Override public void mouseClicked(java.awt.event.MouseEvent e) {
                if (onClick != null) onClick.run();
            }

            @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                ctaLbl.setForeground(NEON_LT);
            }

            @Override public void mouseExited(java.awt.event.MouseEvent e) {
                ctaLbl.setForeground(NEON);
            }
        };
        card.addMouseListener(promoClick);
        ctaLbl.addMouseListener(promoClick);
        return card;
    }

    /**
     Loads product data and stock information from the database.
     */
    private void loadProductsFromDB() {
        java.util.List<Object[]> rows = new java.util.ArrayList<>();
        stockQtyMap.clear();
        stockLimitMap.clear();
        try (java.sql.Connection con = DBConnection.getConnection();
             java.sql.Statement st = con.createStatement();
             java.sql.ResultSet rs = st.executeQuery(
                     "SELECT item_id, name, description, package_type, unit, units_per_pack, price, quantity, stock_limit FROM ipos_ca.stock_items ORDER BY name")) {
            while (rs.next()) {
                int qty = rs.getInt("quantity");
                int lim = rs.getInt("stock_limit");
                String name = rs.getString("name");
                stockQtyMap.put(name, qty);
                stockLimitMap.put(name, lim);
                String status = qty == 0 ? "NO STOCK"
                        : qty < lim ? "LOW STOCK"
                        : "IN STOCK";
                rows.add(new Object[]{
                        rs.getString("item_id"),
                        name,
                        rs.getString("description"),
                        rs.getString("package_type"),
                        rs.getString("unit"),
                        rs.getInt("units_per_pack"),
                        String.format("£%.2f", rs.getDouble("price")),
                        status,
                        "ADD"
                });
            }
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Could not load products: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        allProductData = rows.toArray(new Object[0][]);
    }

    /**
     Builds and styles the product catalogue table.
     */
    private void buildProductTable() {
        String[] cols = {"ITEM_ID", "NAME", "DESCRIPTION", "PACKAGE TYPE", "UNIT", "UNITS/PACK", "PRICE", "STOCK", ""};
        loadProductsFromDB();
        productModel = new DefaultTableModel(allProductData, cols) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        JTable table = new JTable(productModel);
        table.setBackground(PANEL);
        table.setForeground(new Color(255, 255, 255, 200));
        table.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        table.setRowHeight(40);
        table.setShowGrid(false);
        table.setIntercellSpacing(new Dimension(0, 0));
        table.setSelectionBackground(new Color(37, 99, 168, 50));
        table.setSelectionForeground(Color.WHITE);
        table.setFillsViewportHeight(true);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        JTableHeader header = table.getTableHeader();
        header.setBackground(new Color(0x0a1018));
        header.setForeground(NEON);
        header.setFont(new Font("Segoe UI", Font.BOLD, 9));
        header.setPreferredSize(new Dimension(0, 36));
        header.setReorderingAllowed(false);
        header.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37, 99, 168, 60)));

        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer() {
            @Override public Component getTableCellRendererComponent(
                    JTable t, Object v, boolean sel, boolean foc, int r, int c) {
                super.getTableCellRendererComponent(t, v, sel, foc, r, c);
                String stock = t.getModel().getValueAt(r, 7) != null
                        ? t.getModel().getValueAt(r, 7).toString() : "";
                boolean noStock  = "NO STOCK".equals(stock);
                boolean atLimit  = "LIMIT".equals(stock);
                boolean dimmed   = noStock || atLimit;
                if (dimmed) {
                    setBackground(new Color(0x1a0808));
                    setForeground(new Color(255, 255, 255, 80));
                } else {
                    setBackground(r % 2 == 0 ? PANEL : new Color(0x0a1018));
                    setForeground(new Color(255, 255, 255, 200));
                }
                setBorder(BorderFactory.createEmptyBorder(0, 16, 0, 16));
                if (sel) setBackground(new Color(37, 99, 168, 50));
                if (c == 7) {
                    if ("IN STOCK".equals(stock))   setForeground(new Color(0x4ade80));
                    if ("LOW STOCK".equals(stock))  setForeground(new Color(0xfbbf24));
                    if ("NO STOCK".equals(stock))   setForeground(new Color(0xf87171));
                    if ("LIMIT".equals(stock))      setForeground(new Color(0xf97316));
                }
                return this;
            }
        };
        for (int i = 0; i < 8; i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
        }

        table.getColumnModel().getColumn(6).setCellRenderer((t, v, sel, foc, r, c) -> {
            String stock = t.getModel().getValueAt(r, 7) != null
                    ? t.getModel().getValueAt(r, 7).toString() : "";
            boolean noStock = "NO STOCK".equals(stock) || "LIMIT".equals(stock);
            Color bg = noStock ? new Color(0x1a0808) : (r % 2 == 0 ? PANEL : new Color(0x0a1018));
            if (sel) bg = new Color(37, 99, 168, 50);

            String prodName = t.getModel().getValueAt(r, 1) != null
                    ? t.getModel().getValueAt(r, 1).toString() : "";
            PromotionCardData activeCamp = campaignsById.get(activeCampaignId);
            double discountRate = 1.0;

            if (activeCamp != null) {
                Double pct = activeCamp.discountsByProductName.get(prodName);
                if (pct != null) {
                    discountRate = 1.0 - (pct / 100.0);
                }
            }

            boolean promoApplies = discountRate < 1.0 && !noStock;
            boolean loyaltyApplies = OrderManager.isLoyaltyOrder(CartManager.memberEmail) && !noStock;
            boolean applyDiscount = promoApplies || loyaltyApplies;
            JPanel cell = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 16, 0));
            cell.setOpaque(true);
            cell.setBackground(bg);
            cell.setPreferredSize(new java.awt.Dimension(0, 40));
            if (applyDiscount) {
                String orig = v != null ? v.toString() : "";
                try {
                    double price = Double.parseDouble(orig.replace("£", ""));
                    double rate  = (promoApplies ? discountRate : 1.0) * (loyaltyApplies ? 0.9 : 1.0);
                    double disc  = Math.round(price * rate * 100.0) / 100.0;
                    JLabel discLbl = new JLabel(String.format("£%.2f", disc));
                    discLbl.setFont(new Font("Segoe UI", Font.BOLD, 12));
                    discLbl.setForeground(new Color(0x4ade80));
                    JLabel origLbl = new JLabel(orig);
                    origLbl.setFont(new Font("Segoe UI", Font.PLAIN, 10));
                    origLbl.setForeground(new Color(255, 255, 255, 70));
                    cell.add(discLbl);
                    cell.add(origLbl);
                } catch (NumberFormatException ignored) {
                    JLabel lbl = new JLabel(v != null ? v.toString() : "");
                    lbl.setForeground(new Color(255, 255, 255, 200));
                    cell.add(lbl);
                }
            } else {
                JLabel lbl = new JLabel(v != null ? v.toString() : "");
                lbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
                lbl.setForeground(noStock ? new Color(255, 255, 255, 80) : new Color(255, 255, 255, 200));
                cell.add(lbl);
            }
            return cell;
        });

        table.getColumnModel().getColumn(8).setCellRenderer((t, v, sel, foc, r, c) -> {
            String stock = t.getModel().getValueAt(r, 7) != null
                    ? t.getModel().getValueAt(r, 7).toString() : "";
            boolean noStock = "NO STOCK".equals(stock);
            boolean atLimit = "LIMIT".equals(stock);
            boolean blocked = noStock || atLimit;
            JButton btn = new JButton(noStock ? "OUT" : atLimit ? "LIMIT" : "+ ADD");
            btn.setBackground(blocked ? new Color(0x3a1010) : NEON);
            btn.setForeground(blocked ? new Color(255, 255, 255, 70) : Color.WHITE);
            btn.setFont(new Font("Segoe UI", Font.BOLD, 10));
            btn.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
            btn.setFocusPainted(false);
            btn.setOpaque(true);
            JPanel wrap = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 6));
            wrap.setBackground(blocked ? new Color(0x1a0808) : (r % 2 == 0 ? PANEL : new Color(0x0a1018)));
            wrap.add(btn);
            return wrap;
        });
        table.getColumnModel().getColumn(8).setPreferredWidth(90);
        table.getColumnModel().getColumn(8).setMaxWidth(110);

        table.getColumnModel().getColumn(3).setPreferredWidth(110);
        table.getColumnModel().getColumn(3).setMaxWidth(140);
        table.getColumnModel().getColumn(4).setPreferredWidth(80);
        table.getColumnModel().getColumn(4).setMaxWidth(100);
        table.getColumnModel().getColumn(5).setPreferredWidth(80);
        table.getColumnModel().getColumn(5).setMaxWidth(100);
        table.getColumnModel().getColumn(6).setPreferredWidth(110);
        table.getColumnModel().getColumn(6).setMaxWidth(140);
        table.getColumnModel().getColumn(7).setPreferredWidth(110);
        table.getColumnModel().getColumn(7).setMaxWidth(130);
        table.getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setWidth(0);

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseClicked(java.awt.event.MouseEvent e) {
                int col = table.columnAtPoint(e.getPoint());
                int row = table.rowAtPoint(e.getPoint());

                if (row >= 0 && col != 8) {
                    showProductDetailsDialog(row);
                }

                if (col == 8 && row >= 0) {
                    Object stockVal = productModel.getValueAt(row, 7);
                    String stockStr = stockVal != null ? stockVal.toString() : "";
                    if (!"NO STOCK".equals(stockStr) && !"LIMIT".equals(stockStr)) {
                        String prodName  = productModel.getValueAt(row, 1).toString();
                        String priceStr  = productModel.getValueAt(row, 6).toString()
                                .replace("£", "").trim();
                        int limitQty = stockLimitMap.getOrDefault(prodName, Integer.MAX_VALUE);
                        int cartQty  = 0;
                        for (CartManager.CartItem it : CartManager.getItems()) {
                            if (it.name.equals(prodName)) { cartQty = it.qty; break; }
                        }
                        if (cartQty >= limitQty) return;
                        try {
                            double unitPrice = Double.parseDouble(priceStr);

                            double itemRate = 1.0;
                            PromotionCardData activeCamp = campaignsById.get(activeCampaignId);
                            if (activeCamp != null) {
                                Double pct = activeCamp.discountsByProductName.get(prodName);
                                if (pct != null) {
                                    itemRate = 1.0 - (pct / 100.0);
                                }
                            }

                            if (itemRate < 1.0) {
                                unitPrice = Math.round(unitPrice * itemRate * 100.0) / 100.0;
                            }

                            if (OrderManager.isLoyaltyOrder(CartManager.memberEmail)) {
                                unitPrice = Math.round(unitPrice * 0.9 * 100.0) / 100.0;
                            }

                            String itemId = productModel.getValueAt(row, 0).toString();
                            try {
                                boolean isGuest = "Guest".equals(username);
                                String identifier = isGuest ? CartManager.guestToken : CartManager.memberEmail;

                                sendAddToBackend(identifier, itemId, 1, isGuest);

                                if (activeCampaignId != null) {
                                    ActivityLoggerClient.log("ADD_TO_CART", itemId, activeCampaignId, null);
                                }

                            } catch (Exception ex) {
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(
                                        HomePage.this,
                                        "Failed to add item to cart.",
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE
                                );
                            }

                        } catch (NumberFormatException ignored) {}

                        for (Object[] dataRow : allProductData) {
                            dataRow[7] = computeStockStatus(dataRow[1].toString());
                        }
                        filterTable();

                        cartCount++;
                        cartButton.repaint();
                    }
                }
            }
        });

        searchField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override public void insertUpdate(javax.swing.event.DocumentEvent e)  { filterTable(); }
            @Override public void removeUpdate(javax.swing.event.DocumentEvent e)  { filterTable(); }
            @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
        });

        productTable = table;

        promoBannerLbl = new JLabel();
        promoBannerLbl.setFont(new Font("Segoe UI", Font.BOLD, 11));
        promoBannerLbl.setForeground(new Color(0x4ade80));
        promoBannerLbl.setOpaque(true);
        promoBannerLbl.setBackground(new Color(0x0a1f0a));
        promoBannerLbl.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(74, 222, 128, 60)),
                BorderFactory.createEmptyBorder(6, 14, 6, 14)));
        promoBannerLbl.setAlignmentX(LEFT_ALIGNMENT);
        promoBannerLbl.setMaximumSize(new Dimension(Integer.MAX_VALUE, 36));
        promoBannerLbl.setVisible(false);
        cataloguePanel.add(promoBannerLbl);

        loyaltyBannerLbl = new JLabel(
                "  LOYALTY REWARD — This is your 10th order! 10% off everything. Prices below include your discount.");
        loyaltyBannerLbl.setFont(new Font("Segoe UI", Font.BOLD, 11));
        loyaltyBannerLbl.setForeground(new Color(0xfbbf24));
        loyaltyBannerLbl.setOpaque(true);
        loyaltyBannerLbl.setBackground(new Color(0x1a1200));
        loyaltyBannerLbl.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(251, 191, 36, 60)),
                BorderFactory.createEmptyBorder(6, 14, 6, 14)));
        loyaltyBannerLbl.setAlignmentX(LEFT_ALIGNMENT);
        loyaltyBannerLbl.setMaximumSize(new Dimension(Integer.MAX_VALUE, 36));
        loyaltyBannerLbl.setVisible(OrderManager.isLoyaltyOrder(CartManager.memberEmail));
        cataloguePanel.add(loyaltyBannerLbl);

        JScrollPane sp = new JScrollPane(table);
        sp.setBorder(BorderFactory.createLineBorder(new Color(37, 99, 168, 60), 1));
        sp.getViewport().setBackground(PANEL);
        sp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        sp.setAlignmentX(LEFT_ALIGNMENT);
        sp.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));

        cataloguePanel.add(sp);
        cataloguePanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));
    }

    /**
     Shows a dialog with full details for the selected product.
     */
    private void showProductDetailsDialog(int row) {
        if (row < 0 || row >= productModel.getRowCount()) return;

        String itemId       = String.valueOf(productModel.getValueAt(row, 0));
        String name         = String.valueOf(productModel.getValueAt(row, 1));
        String description  = String.valueOf(productModel.getValueAt(row, 2));
        String packageType  = String.valueOf(productModel.getValueAt(row, 3));
        String unit         = String.valueOf(productModel.getValueAt(row, 4));
        String unitsPerPack = String.valueOf(productModel.getValueAt(row, 5));
        String price        = String.valueOf(productModel.getValueAt(row, 6));
        String stock        = String.valueOf(productModel.getValueAt(row, 7));

        if (activeCampaignId != null) {
            ActivityLoggerClient.log("ITEM_VIEW", itemId, activeCampaignId, null);
        }

        JDialog dlg = new JDialog(this, "Product Details", true);
        dlg.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dlg.setSize(520, 420);
        dlg.setLocationRelativeTo(this);

        JPanel root = new JPanel();
        root.setBackground(PANEL);
        root.setLayout(new BoxLayout(root, BoxLayout.Y_AXIS));
        root.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(37, 99, 168, 80), 1),
                BorderFactory.createEmptyBorder(20, 24, 20, 24)
        ));

        JLabel titleLbl = new JLabel(name);
        titleLbl.setFont(new Font("Trebuchet MS", Font.BOLD, 20));
        titleLbl.setForeground(Color.WHITE);
        titleLbl.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel idLbl = new JLabel("Item ID: " + itemId);
        idLbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        idLbl.setForeground(new Color(255, 255, 255, 110));
        idLbl.setAlignmentX(Component.LEFT_ALIGNMENT);

        root.add(titleLbl);
        root.add(Box.createVerticalStrut(6));
        root.add(idLbl);
        root.add(Box.createVerticalStrut(18));

        root.add(makeDetailLabel("Description: " + description));
        root.add(Box.createVerticalStrut(8));
        root.add(makeDetailLabel("Package Type: " + packageType));
        root.add(Box.createVerticalStrut(8));
        root.add(makeDetailLabel("Unit: " + unit));
        root.add(Box.createVerticalStrut(8));
        root.add(makeDetailLabel("Units per Pack: " + unitsPerPack));
        root.add(Box.createVerticalStrut(8));
        root.add(makeDetailLabel("Price: " + price));
        root.add(Box.createVerticalStrut(8));
        root.add(makeDetailLabel("Stock Status: " + stock));

        if (activeCampaignId!= null) {
            PromoManager.Campaign activeCamp = PromoManager.getCampaign(activePromo);
            double discountRate = activeCamp != null
                    ? PromoManager.getItemDiscountRate(activePromo, name) : 1.0;
            if (discountRate < 1.0) {
                try {
                    double originalPrice = Double.parseDouble(price.replace("£", "").trim());
                    double discountedPrice = Math.round(originalPrice * discountRate * 100.0) / 100.0;
                    root.add(Box.createVerticalStrut(8));
                    JLabel promoLbl = new JLabel("Promo Price: " + String.format("£%.2f", discountedPrice));
                    promoLbl.setFont(new Font("Segoe UI", Font.BOLD, 13));
                    promoLbl.setForeground(new Color(0x4ade80));
                    promoLbl.setAlignmentX(Component.LEFT_ALIGNMENT);
                    root.add(promoLbl);
                } catch (NumberFormatException ignored) {}
            }
        }

        root.add(Box.createVerticalGlue());
        root.add(Box.createVerticalStrut(18));

        JPanel buttonRow = new JPanel(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        buttonRow.setOpaque(false);
        buttonRow.setAlignmentX(Component.LEFT_ALIGNMENT);

        JButton closeBtn = new JButton("Close");
        closeBtn.setBackground(new Color(0x0b1220));
        closeBtn.setForeground(Color.WHITE);
        closeBtn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        closeBtn.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(37, 99, 168, 80), 1),
                BorderFactory.createEmptyBorder(8, 18, 8, 18)
        ));
        closeBtn.setFocusPainted(false);
        closeBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        closeBtn.addActionListener(e -> dlg.dispose());

        buttonRow.add(closeBtn);
        root.add(buttonRow);

        dlg.setContentPane(root);
        dlg.setVisible(true);
    }

    /**
     Creates a detail label for the product information dialog.
     */
    private JLabel makeDetailLabel(String text) {
        JLabel lbl = new JLabel(text);
        lbl.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lbl.setForeground(new Color(255, 255, 255, 190));
        lbl.setAlignmentX(Component.LEFT_ALIGNMENT);
        return lbl;
    }

    /**
     Builds the customer services section shown for signed-in users.
     */
    private JPanel buildCustomerServices() {
        JPanel section = new JPanel();
        section.setOpaque(false);
        section.setLayout(new BoxLayout(section, BoxLayout.Y_AXIS));
        section.setAlignmentX(LEFT_ALIGNMENT);

        JLabel secLabel = new JLabel("CUSTOMER SERVICES");
        secLabel.setFont(new Font("Segoe UI", Font.BOLD, 11));
        secLabel.setForeground(NEON);
        secLabel.setAlignmentX(LEFT_ALIGNMENT);
        secLabel.setBorder(BorderFactory.createEmptyBorder(0, 0, 12, 0));
        section.add(secLabel);

        JPanel btnRow = new JPanel(new GridLayout(1, 4, 14, 0));
        btnRow.setOpaque(false);
        btnRow.setAlignmentX(LEFT_ALIGNMENT);
        btnRow.setMaximumSize(new Dimension(Integer.MAX_VALUE, 80));

        btnRow.add(makeServiceCard("Track Order",     () -> { dispose(); new TrackOrderPage(username).setVisible(true); }));
        btnRow.add(makeServiceCard("My Orders",       () -> { dispose(); new MyOrdersPage(username).setVisible(true); }));
        btnRow.add(makeServiceCard("View Invoices",   () -> { dispose(); new ViewInvoicesPage(username).setVisible(true); }));
        btnRow.add(makeServiceCard("Manage Account",  () -> { dispose(); new ManageAccountPage(username).setVisible(true); }));

        section.add(btnRow);
        return section;
    }

    /**
     Builds a clickable service card for the customer services section.
     */
    private JPanel makeServiceCard(String label, Runnable onClick) {
        JPanel card = new JPanel() {
            @Override protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(PANEL);
                g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 10, 10));
                g2.setColor(new Color(37, 99, 168, 60));
                g2.setStroke(new BasicStroke(1f));
                g2.draw(new RoundRectangle2D.Float(0.5f, 0.5f, getWidth()-1f, getHeight()-1f, 10, 10));
                g2.dispose();
            }
        };
        card.setOpaque(false);
        card.setLayout(new GridBagLayout());
        card.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        JLabel textLbl = new JLabel(label, SwingConstants.CENTER);
        textLbl.setFont(new Font("Segoe UI", Font.BOLD, 14));
        textLbl.setForeground(Color.WHITE);

        card.add(textLbl, new GridBagConstraints());

        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseClicked(java.awt.event.MouseEvent e) {
                if (onClick != null) onClick.run();
            }
            @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                textLbl.setForeground(NEON_LT);
                card.repaint();
            }
            @Override public void mouseExited(java.awt.event.MouseEvent e) {
                textLbl.setForeground(Color.WHITE);
                card.repaint();
            }
        });

        return card;
    }

    /**
     Calculates the stock status shown for a product.
     */
    private String computeStockStatus(String name) {
        int dbQty  = stockQtyMap.getOrDefault(name, 0);
        int lim    = stockLimitMap.getOrDefault(name, Integer.MAX_VALUE);
        int cartQty = 0;
        for (CartManager.CartItem it : CartManager.getItems()) {
            if (it.name.equals(name)) { cartQty = it.qty; break; }
        }
        if (dbQty == 0) return "NO STOCK";
        if (cartQty >= lim) return "LIMIT";
        if (dbQty < lim)    return "LOW STOCK";
        return "IN STOCK";
    }

    /**
     Filters the product table using the current search text.
     */
    private void filterTable() {
        if (productModel == null || allProductData == null) return;
        String query = searchField.getText().toLowerCase().trim();
        productModel.setRowCount(0);
        for (Object[] row : allProductData) {
            boolean matchesSearch = query.isEmpty()
                    || row[1].toString().toLowerCase().contains(query)
                    || row[2].toString().toLowerCase().contains(query);
            if (matchesSearch) {
                productModel.addRow(row);
            }
        }
        if (productTable != null) productTable.repaint();
    }

    /**
     Activates a promotion campaign and refreshes the catalogue view.
     */
    private void activatePromo(Integer campaignId) {
        activeCampaignId = campaignId;
        CartManager.activeCampaignId = campaignId;

        ActivityLoggerClient.log("CAMPAIGN_VIEW", null, campaignId, null);

        searchField.setText("");
        filterTable();
        updatePromoBanner();
    }

    /**
     Updates the promotion banner for the currently active campaign.
     */
    private void updatePromoBanner() {
        if (promoBannerLbl == null) return;

        if (activeCampaignId == null) {
            promoBannerLbl.setVisible(false);
            return;
        }

        PromotionCardData camp = campaignsById.get(activeCampaignId);
        if (camp != null) {
            StringBuilder sb = new StringBuilder();
            for (java.util.Map.Entry<String, Double> e : camp.discountsByProductName.entrySet()) {
                if (sb.length() > 0) sb.append(", ");
                sb.append(e.getKey()).append(" (").append((int) Math.round(e.getValue())).append("% off)");
            }

            String items = sb.length() > 0 ? sb.toString() : "selected items";
            promoBannerLbl.setText("  PROMO ACTIVE — " + camp.campaignName
                    + ". Discounts on: " + items + ". Discounted prices shown below.");
        }

        promoBannerLbl.setVisible(true);
        cataloguePanel.revalidate();
    }

    /**
     Returns the initials used in the user avatar.
     */
    private String getInitials(String name) {
        if (name == null || name.trim().isEmpty()) return "G";
        String[] parts = name.trim().split("\\s+");
        if (parts.length >= 2)
            return ("" + parts[0].charAt(0) + parts[1].charAt(0)).toUpperCase();
        return name.substring(0, Math.min(2, name.length())).toUpperCase();
    }

    /**
     Builds the avatar panel shown in the top navigation bar.
     */
    private JPanel makeAvatarPanel() {
        String initials = getInitials(username);
        JPanel av = new JPanel() {
            @Override protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(NEON);
                g2.fillOval(0, 0, getWidth() - 1, getHeight() - 1);
                g2.setColor(Color.WHITE);
                g2.setFont(new Font("Segoe UI", Font.BOLD, 13));
                FontMetrics fm = g2.getFontMetrics();
                g2.drawString(initials,
                        (getWidth()  - fm.stringWidth(initials)) / 2,
                        (getHeight() + fm.getAscent() - fm.getDescent()) / 2);
                g2.dispose();
            }
        };
        av.setOpaque(false);
        av.setPreferredSize(new Dimension(36, 36));
        av.setMaximumSize(new Dimension(36, 36));
        av.setMinimumSize(new Dimension(36, 36));
        return av;
    }

    /**
     Sends an add-to-cart request to the backend for a member or guest cart.
     */
    private void sendAddToBackend(String identifier, String itemId, int qty, boolean isGuest) throws Exception {
        if (isGuest && (CartManager.guestToken == null || CartManager.guestToken.trim().isEmpty())) {
            CartManager.createGuestCartOnBackend();
            identifier = CartManager.guestToken;
        }

        if (!isGuest && (CartManager.memberEmail == null || CartManager.memberEmail.trim().isEmpty())) {
            throw new Exception("memberEmail is null. Set CartManager.memberEmail when the member logs in.");
        }

        String json = isGuest
                ? "{\"guestToken\":\"" + identifier + "\",\"itemId\":\"" + itemId + "\",\"qty\":" + qty + "}"
                : "{\"memberEmail\":\"" + identifier + "\",\"itemId\":\"" + itemId + "\",\"qty\":" + qty + "}";

        URL url = new URL("http://localhost:8080/api/cart/add");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setDoOutput(true);

        try (OutputStream os = conn.getOutputStream()) {
            os.write(json.getBytes());
        }

        int status = conn.getResponseCode();
        String response = "";
        try {
            response = new String(
                    (status >= 200 && status < 300 ? conn.getInputStream() : conn.getErrorStream()).readAllBytes()
            );
        } catch (Exception ignored) {}

        System.out.println("ADD TO CART status = " + status);
        System.out.println("ADD TO CART response = " + response);
        System.out.println("ADD TO CART json = " + json);

        if (status >= 400) {
            throw new Exception("Failed to add item. HTTP " + status + " -> " + response);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton cartButton;
    private javax.swing.JPanel cataloguePanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel filterRow;
    private javax.swing.JScrollPane mainScroll;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel promoPanel;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel sectionPromoLabel;
    private javax.swing.JButton signOutButton;
// End of variables declaration//GEN-END:variables
}