db.url=jdbc:mysql://localhost:3306/ipos_pu?useSSL=false&serverTimezone=UTC
db.user=root
<<<<<<< Updated upstream:2nd Deliverable/ipos-pu/backend/src/main/resources/config.example.properties
db.password=YOUR_PASSWORD_HERE
=======
db.password=4289r
>>>>>>> Stashed changes:out/production/SyDi/config.properties
